// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// JFCppTree
List JFCppTree(uint tree_type, DataFrame df, unsigned int mtry, unsigned int min_node_size, unsigned int nsplits, CharacterVector splitrule, bool honest, NumericVector response_indices, NumericVector feature_indices, LogicalVector categorical, NumericVector unique, unsigned int seed, size_t num_event_times);
RcppExport SEXP _JumpForests_JFCppTree(SEXP tree_typeSEXP, SEXP dfSEXP, SEXP mtrySEXP, SEXP min_node_sizeSEXP, SEXP nsplitsSEXP, SEXP splitruleSEXP, SEXP honestSEXP, SEXP response_indicesSEXP, SEXP feature_indicesSEXP, SEXP categoricalSEXP, SEXP uniqueSEXP, SEXP seedSEXP, SEXP num_event_timesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< uint >::type tree_type(tree_typeSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type df(dfSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type mtry(mtrySEXP);
    Rcpp::traits::input_parameter< unsigned int >::type min_node_size(min_node_sizeSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type nsplits(nsplitsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type splitrule(splitruleSEXP);
    Rcpp::traits::input_parameter< bool >::type honest(honestSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type response_indices(response_indicesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type feature_indices(feature_indicesSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type categorical(categoricalSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type unique(uniqueSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< size_t >::type num_event_times(num_event_timesSEXP);
    rcpp_result_gen = Rcpp::wrap(JFCppTree(tree_type, df, mtry, min_node_size, nsplits, splitrule, honest, response_indices, feature_indices, categorical, unique, seed, num_event_times));
    return rcpp_result_gen;
END_RCPP
}
// JFCppTreeMM
List JFCppTreeMM(List jump_data, uint8_t max_response_length, uint8_t num_states, DataFrame df_features, unsigned int mtry, unsigned int min_node_size, unsigned int nsplits, CharacterVector splitrule, bool honest, NumericVector feature_indices, LogicalVector categorical, NumericVector unique, unsigned int seed, size_t num_event_times);
RcppExport SEXP _JumpForests_JFCppTreeMM(SEXP jump_dataSEXP, SEXP max_response_lengthSEXP, SEXP num_statesSEXP, SEXP df_featuresSEXP, SEXP mtrySEXP, SEXP min_node_sizeSEXP, SEXP nsplitsSEXP, SEXP splitruleSEXP, SEXP honestSEXP, SEXP feature_indicesSEXP, SEXP categoricalSEXP, SEXP uniqueSEXP, SEXP seedSEXP, SEXP num_event_timesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type jump_data(jump_dataSEXP);
    Rcpp::traits::input_parameter< uint8_t >::type max_response_length(max_response_lengthSEXP);
    Rcpp::traits::input_parameter< uint8_t >::type num_states(num_statesSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type df_features(df_featuresSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type mtry(mtrySEXP);
    Rcpp::traits::input_parameter< unsigned int >::type min_node_size(min_node_sizeSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type nsplits(nsplitsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type splitrule(splitruleSEXP);
    Rcpp::traits::input_parameter< bool >::type honest(honestSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type feature_indices(feature_indicesSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type categorical(categoricalSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type unique(uniqueSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< size_t >::type num_event_times(num_event_timesSEXP);
    rcpp_result_gen = Rcpp::wrap(JFCppTreeMM(jump_data, max_response_length, num_states, df_features, mtry, min_node_size, nsplits, splitrule, honest, feature_indices, categorical, unique, seed, num_event_times));
    return rcpp_result_gen;
END_RCPP
}
// JFCppTreePredict
NumericMatrix JFCppTreePredict(const List& JFTree, DataFrame df, NumericVector feature_indices, LogicalVector categorical, NumericVector unique);
RcppExport SEXP _JumpForests_JFCppTreePredict(SEXP JFTreeSEXP, SEXP dfSEXP, SEXP feature_indicesSEXP, SEXP categoricalSEXP, SEXP uniqueSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type JFTree(JFTreeSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type df(dfSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type feature_indices(feature_indicesSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type categorical(categoricalSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type unique(uniqueSEXP);
    rcpp_result_gen = Rcpp::wrap(JFCppTreePredict(JFTree, df, feature_indices, categorical, unique));
    return rcpp_result_gen;
END_RCPP
}
// JFCppTreePredictMM
List JFCppTreePredictMM(const List& JFTree, DataFrame df, NumericVector feature_indices, LogicalVector categorical, NumericVector unique);
RcppExport SEXP _JumpForests_JFCppTreePredictMM(SEXP JFTreeSEXP, SEXP dfSEXP, SEXP feature_indicesSEXP, SEXP categoricalSEXP, SEXP uniqueSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type JFTree(JFTreeSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type df(dfSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type feature_indices(feature_indicesSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type categorical(categoricalSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type unique(uniqueSEXP);
    rcpp_result_gen = Rcpp::wrap(JFCppTreePredictMM(JFTree, df, feature_indices, categorical, unique));
    return rcpp_result_gen;
END_RCPP
}
// JFCppTreeError
List JFCppTreeError(const List& JFTree, DataFrame df, NumericVector feature_indices, LogicalVector categorical, NumericVector unique, NumericVector response_indices);
RcppExport SEXP _JumpForests_JFCppTreeError(SEXP JFTreeSEXP, SEXP dfSEXP, SEXP feature_indicesSEXP, SEXP categoricalSEXP, SEXP uniqueSEXP, SEXP response_indicesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type JFTree(JFTreeSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type df(dfSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type feature_indices(feature_indicesSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type categorical(categoricalSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type unique(uniqueSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type response_indices(response_indicesSEXP);
    rcpp_result_gen = Rcpp::wrap(JFCppTreeError(JFTree, df, feature_indices, categorical, unique, response_indices));
    return rcpp_result_gen;
END_RCPP
}
// JFCppForest
List JFCppForest(uint tree_type, DataFrame df, unsigned int mtry, unsigned int min_node_size, unsigned int nsplits, CharacterVector splitrule, unsigned int ntrees, bool honest, bool swr, double sample_rate, NumericVector response_indices, NumericVector feature_indices, LogicalVector categorical, NumericVector unique, unsigned int seed, unsigned int nworkers, size_t num_event_times);
RcppExport SEXP _JumpForests_JFCppForest(SEXP tree_typeSEXP, SEXP dfSEXP, SEXP mtrySEXP, SEXP min_node_sizeSEXP, SEXP nsplitsSEXP, SEXP splitruleSEXP, SEXP ntreesSEXP, SEXP honestSEXP, SEXP swrSEXP, SEXP sample_rateSEXP, SEXP response_indicesSEXP, SEXP feature_indicesSEXP, SEXP categoricalSEXP, SEXP uniqueSEXP, SEXP seedSEXP, SEXP nworkersSEXP, SEXP num_event_timesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< uint >::type tree_type(tree_typeSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type df(dfSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type mtry(mtrySEXP);
    Rcpp::traits::input_parameter< unsigned int >::type min_node_size(min_node_sizeSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type nsplits(nsplitsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type splitrule(splitruleSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type ntrees(ntreesSEXP);
    Rcpp::traits::input_parameter< bool >::type honest(honestSEXP);
    Rcpp::traits::input_parameter< bool >::type swr(swrSEXP);
    Rcpp::traits::input_parameter< double >::type sample_rate(sample_rateSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type response_indices(response_indicesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type feature_indices(feature_indicesSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type categorical(categoricalSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type unique(uniqueSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type nworkers(nworkersSEXP);
    Rcpp::traits::input_parameter< size_t >::type num_event_times(num_event_timesSEXP);
    rcpp_result_gen = Rcpp::wrap(JFCppForest(tree_type, df, mtry, min_node_size, nsplits, splitrule, ntrees, honest, swr, sample_rate, response_indices, feature_indices, categorical, unique, seed, nworkers, num_event_times));
    return rcpp_result_gen;
END_RCPP
}
// JFCppForestMM
List JFCppForestMM(List jump_data, uint8_t max_response_length, uint8_t num_states, DataFrame df_features, unsigned int mtry, unsigned int min_node_size, unsigned int nsplits, CharacterVector splitrule, unsigned int ntrees, bool honest, bool swr, double sample_rate, NumericVector feature_indices, LogicalVector categorical, NumericVector unique, unsigned int seed, unsigned int nworkers, bool save_predictions, size_t num_event_times);
RcppExport SEXP _JumpForests_JFCppForestMM(SEXP jump_dataSEXP, SEXP max_response_lengthSEXP, SEXP num_statesSEXP, SEXP df_featuresSEXP, SEXP mtrySEXP, SEXP min_node_sizeSEXP, SEXP nsplitsSEXP, SEXP splitruleSEXP, SEXP ntreesSEXP, SEXP honestSEXP, SEXP swrSEXP, SEXP sample_rateSEXP, SEXP feature_indicesSEXP, SEXP categoricalSEXP, SEXP uniqueSEXP, SEXP seedSEXP, SEXP nworkersSEXP, SEXP save_predictionsSEXP, SEXP num_event_timesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type jump_data(jump_dataSEXP);
    Rcpp::traits::input_parameter< uint8_t >::type max_response_length(max_response_lengthSEXP);
    Rcpp::traits::input_parameter< uint8_t >::type num_states(num_statesSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type df_features(df_featuresSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type mtry(mtrySEXP);
    Rcpp::traits::input_parameter< unsigned int >::type min_node_size(min_node_sizeSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type nsplits(nsplitsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type splitrule(splitruleSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type ntrees(ntreesSEXP);
    Rcpp::traits::input_parameter< bool >::type honest(honestSEXP);
    Rcpp::traits::input_parameter< bool >::type swr(swrSEXP);
    Rcpp::traits::input_parameter< double >::type sample_rate(sample_rateSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type feature_indices(feature_indicesSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type categorical(categoricalSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type unique(uniqueSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type nworkers(nworkersSEXP);
    Rcpp::traits::input_parameter< bool >::type save_predictions(save_predictionsSEXP);
    Rcpp::traits::input_parameter< size_t >::type num_event_times(num_event_timesSEXP);
    rcpp_result_gen = Rcpp::wrap(JFCppForestMM(jump_data, max_response_length, num_states, df_features, mtry, min_node_size, nsplits, splitrule, ntrees, honest, swr, sample_rate, feature_indices, categorical, unique, seed, nworkers, save_predictions, num_event_times));
    return rcpp_result_gen;
END_RCPP
}
// JFCppForestPredict
NumericMatrix JFCppForestPredict(const List& JFForest, DataFrame df, NumericVector feature_indices, LogicalVector categorical, NumericVector unique);
RcppExport SEXP _JumpForests_JFCppForestPredict(SEXP JFForestSEXP, SEXP dfSEXP, SEXP feature_indicesSEXP, SEXP categoricalSEXP, SEXP uniqueSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type JFForest(JFForestSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type df(dfSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type feature_indices(feature_indicesSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type categorical(categoricalSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type unique(uniqueSEXP);
    rcpp_result_gen = Rcpp::wrap(JFCppForestPredict(JFForest, df, feature_indices, categorical, unique));
    return rcpp_result_gen;
END_RCPP
}
// JFCppForestPredictMM
List JFCppForestPredictMM(const List& JFForest, DataFrame df, NumericVector feature_indices, LogicalVector categorical, NumericVector unique);
RcppExport SEXP _JumpForests_JFCppForestPredictMM(SEXP JFForestSEXP, SEXP dfSEXP, SEXP feature_indicesSEXP, SEXP categoricalSEXP, SEXP uniqueSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type JFForest(JFForestSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type df(dfSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type feature_indices(feature_indicesSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type categorical(categoricalSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type unique(uniqueSEXP);
    rcpp_result_gen = Rcpp::wrap(JFCppForestPredictMM(JFForest, df, feature_indices, categorical, unique));
    return rcpp_result_gen;
END_RCPP
}
// JFCppForestError
List JFCppForestError(const List& JFForest, DataFrame df, NumericVector feature_indices, LogicalVector categorical, NumericVector unique, NumericVector response_indices);
RcppExport SEXP _JumpForests_JFCppForestError(SEXP JFForestSEXP, SEXP dfSEXP, SEXP feature_indicesSEXP, SEXP categoricalSEXP, SEXP uniqueSEXP, SEXP response_indicesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type JFForest(JFForestSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type df(dfSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type feature_indices(feature_indicesSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type categorical(categoricalSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type unique(uniqueSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type response_indices(response_indicesSEXP);
    rcpp_result_gen = Rcpp::wrap(JFCppForestError(JFForest, df, feature_indices, categorical, unique, response_indices));
    return rcpp_result_gen;
END_RCPP
}
// JFCppForestVIMPFeature
double JFCppForestVIMPFeature(const List& JFForest, CharacterVector feature_name, int feature_seed, CharacterVector method);
RcppExport SEXP _JumpForests_JFCppForestVIMPFeature(SEXP JFForestSEXP, SEXP feature_nameSEXP, SEXP feature_seedSEXP, SEXP methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type JFForest(JFForestSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type feature_name(feature_nameSEXP);
    Rcpp::traits::input_parameter< int >::type feature_seed(feature_seedSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type method(methodSEXP);
    rcpp_result_gen = Rcpp::wrap(JFCppForestVIMPFeature(JFForest, feature_name, feature_seed, method));
    return rcpp_result_gen;
END_RCPP
}
// JFCppForestVIMP
List JFCppForestVIMP(List& JFForest, int seed, CharacterVector method);
RcppExport SEXP _JumpForests_JFCppForestVIMP(SEXP JFForestSEXP, SEXP seedSEXP, SEXP methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List& >::type JFForest(JFForestSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type method(methodSEXP);
    rcpp_result_gen = Rcpp::wrap(JFCppForestVIMP(JFForest, seed, method));
    return rcpp_result_gen;
END_RCPP
}
// getTreeTable
List getTreeTable(SEXP tree_sexp);
RcppExport SEXP _JumpForests_getTreeTable(SEXP tree_sexpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type tree_sexp(tree_sexpSEXP);
    rcpp_result_gen = Rcpp::wrap(getTreeTable(tree_sexp));
    return rcpp_result_gen;
END_RCPP
}
// df_test
void df_test(DataFrame data, NumericVector response_indices, NumericVector feature_indices, LogicalVector categorical, NumericVector unique);
RcppExport SEXP _JumpForests_df_test(SEXP dataSEXP, SEXP response_indicesSEXP, SEXP feature_indicesSEXP, SEXP categoricalSEXP, SEXP uniqueSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type data(dataSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type response_indices(response_indicesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type feature_indices(feature_indicesSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type categorical(categoricalSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type unique(uniqueSEXP);
    df_test(data, response_indices, feature_indices, categorical, unique);
    return R_NilValue;
END_RCPP
}
// testData
void testData(const DataFrame& df, const NumericVector& response_indices, const NumericVector& feature_indices, const LogicalVector& categorical, const NumericVector& unique);
RcppExport SEXP _JumpForests_testData(SEXP dfSEXP, SEXP response_indicesSEXP, SEXP feature_indicesSEXP, SEXP categoricalSEXP, SEXP uniqueSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const DataFrame& >::type df(dfSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type response_indices(response_indicesSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type feature_indices(feature_indicesSEXP);
    Rcpp::traits::input_parameter< const LogicalVector& >::type categorical(categoricalSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type unique(uniqueSEXP);
    testData(df, response_indices, feature_indices, categorical, unique);
    return R_NilValue;
END_RCPP
}
// testDataMM
void testDataMM(const List& jump_data, uint8_t max_response_length, uint8_t num_states, DataFrame& feature_df, const NumericVector& feature_indices, const LogicalVector& categorical, const NumericVector& unique);
RcppExport SEXP _JumpForests_testDataMM(SEXP jump_dataSEXP, SEXP max_response_lengthSEXP, SEXP num_statesSEXP, SEXP feature_dfSEXP, SEXP feature_indicesSEXP, SEXP categoricalSEXP, SEXP uniqueSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type jump_data(jump_dataSEXP);
    Rcpp::traits::input_parameter< uint8_t >::type max_response_length(max_response_lengthSEXP);
    Rcpp::traits::input_parameter< uint8_t >::type num_states(num_statesSEXP);
    Rcpp::traits::input_parameter< DataFrame& >::type feature_df(feature_dfSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type feature_indices(feature_indicesSEXP);
    Rcpp::traits::input_parameter< const LogicalVector& >::type categorical(categoricalSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type unique(uniqueSEXP);
    testDataMM(jump_data, max_response_length, num_states, feature_df, feature_indices, categorical, unique);
    return R_NilValue;
END_RCPP
}
// testUniqueEventTimesThinning
List testUniqueEventTimesThinning(const NumericVector& unique_event_times, size_t num_event_times);
RcppExport SEXP _JumpForests_testUniqueEventTimesThinning(SEXP unique_event_timesSEXP, SEXP num_event_timesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type unique_event_times(unique_event_timesSEXP);
    Rcpp::traits::input_parameter< size_t >::type num_event_times(num_event_timesSEXP);
    rcpp_result_gen = Rcpp::wrap(testUniqueEventTimesThinning(unique_event_times, num_event_times));
    return rcpp_result_gen;
END_RCPP
}
// test_omp
void test_omp();
RcppExport SEXP _JumpForests_test_omp() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    test_omp();
    return R_NilValue;
END_RCPP
}
// testList
List testList();
RcppExport SEXP _JumpForests_testList() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(testList());
    return rcpp_result_gen;
END_RCPP
}
// extract_column
int extract_column(DataFrame data, size_t index);
RcppExport SEXP _JumpForests_extract_column(SEXP dataSEXP, SEXP indexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type data(dataSEXP);
    Rcpp::traits::input_parameter< size_t >::type index(indexSEXP);
    rcpp_result_gen = Rcpp::wrap(extract_column(data, index));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP _JumpForests_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello_world());
    return rcpp_result_gen;
END_RCPP
}
// square_cpp
double square_cpp(double x);
RcppExport SEXP _JumpForests_square_cpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(square_cpp(x));
    return rcpp_result_gen;
END_RCPP
}
// timesTwoMatrix
NumericMatrix timesTwoMatrix(NumericMatrix mat);
RcppExport SEXP _JumpForests_timesTwoMatrix(SEXP matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat(matSEXP);
    rcpp_result_gen = Rcpp::wrap(timesTwoMatrix(mat));
    return rcpp_result_gen;
END_RCPP
}
// sampler
void sampler(int n, int k);
RcppExport SEXP _JumpForests_sampler(SEXP nSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    sampler(n, k);
    return R_NilValue;
END_RCPP
}
// silly_sampler
void silly_sampler(int k);
RcppExport SEXP _JumpForests_silly_sampler(SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    silly_sampler(k);
    return R_NilValue;
END_RCPP
}
// sampler_wrapper
void sampler_wrapper(int n, int k, bool wr);
RcppExport SEXP _JumpForests_sampler_wrapper(SEXP nSEXP, SEXP kSEXP, SEXP wrSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< bool >::type wr(wrSEXP);
    sampler_wrapper(n, k, wr);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_JumpForests_JFCppTree", (DL_FUNC) &_JumpForests_JFCppTree, 13},
    {"_JumpForests_JFCppTreeMM", (DL_FUNC) &_JumpForests_JFCppTreeMM, 14},
    {"_JumpForests_JFCppTreePredict", (DL_FUNC) &_JumpForests_JFCppTreePredict, 5},
    {"_JumpForests_JFCppTreePredictMM", (DL_FUNC) &_JumpForests_JFCppTreePredictMM, 5},
    {"_JumpForests_JFCppTreeError", (DL_FUNC) &_JumpForests_JFCppTreeError, 6},
    {"_JumpForests_JFCppForest", (DL_FUNC) &_JumpForests_JFCppForest, 17},
    {"_JumpForests_JFCppForestMM", (DL_FUNC) &_JumpForests_JFCppForestMM, 19},
    {"_JumpForests_JFCppForestPredict", (DL_FUNC) &_JumpForests_JFCppForestPredict, 5},
    {"_JumpForests_JFCppForestPredictMM", (DL_FUNC) &_JumpForests_JFCppForestPredictMM, 5},
    {"_JumpForests_JFCppForestError", (DL_FUNC) &_JumpForests_JFCppForestError, 6},
    {"_JumpForests_JFCppForestVIMPFeature", (DL_FUNC) &_JumpForests_JFCppForestVIMPFeature, 4},
    {"_JumpForests_JFCppForestVIMP", (DL_FUNC) &_JumpForests_JFCppForestVIMP, 3},
    {"_JumpForests_getTreeTable", (DL_FUNC) &_JumpForests_getTreeTable, 1},
    {"_JumpForests_df_test", (DL_FUNC) &_JumpForests_df_test, 5},
    {"_JumpForests_testData", (DL_FUNC) &_JumpForests_testData, 5},
    {"_JumpForests_testDataMM", (DL_FUNC) &_JumpForests_testDataMM, 7},
    {"_JumpForests_testUniqueEventTimesThinning", (DL_FUNC) &_JumpForests_testUniqueEventTimesThinning, 2},
    {"_JumpForests_test_omp", (DL_FUNC) &_JumpForests_test_omp, 0},
    {"_JumpForests_testList", (DL_FUNC) &_JumpForests_testList, 0},
    {"_JumpForests_extract_column", (DL_FUNC) &_JumpForests_extract_column, 2},
    {"_JumpForests_rcpp_hello_world", (DL_FUNC) &_JumpForests_rcpp_hello_world, 0},
    {"_JumpForests_square_cpp", (DL_FUNC) &_JumpForests_square_cpp, 1},
    {"_JumpForests_timesTwoMatrix", (DL_FUNC) &_JumpForests_timesTwoMatrix, 1},
    {"_JumpForests_sampler", (DL_FUNC) &_JumpForests_sampler, 2},
    {"_JumpForests_silly_sampler", (DL_FUNC) &_JumpForests_silly_sampler, 1},
    {"_JumpForests_sampler_wrapper", (DL_FUNC) &_JumpForests_sampler_wrapper, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_JumpForests(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
