// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// JFCppTree
List JFCppTree(unsigned int tree_type, DataFrame df, unsigned int mtry, unsigned int min_node_size, double max_depth, unsigned int nsplits, CharacterVector splitrule, bool honest, NumericVector response_indices, NumericVector feature_indices, LogicalVector categorical, NumericVector unique, unsigned int seed, size_t num_event_times, NumericVector splitrule_par);
RcppExport SEXP _JumpForests_JFCppTree(SEXP tree_typeSEXP, SEXP dfSEXP, SEXP mtrySEXP, SEXP min_node_sizeSEXP, SEXP max_depthSEXP, SEXP nsplitsSEXP, SEXP splitruleSEXP, SEXP honestSEXP, SEXP response_indicesSEXP, SEXP feature_indicesSEXP, SEXP categoricalSEXP, SEXP uniqueSEXP, SEXP seedSEXP, SEXP num_event_timesSEXP, SEXP splitrule_parSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< unsigned int >::type tree_type(tree_typeSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type df(dfSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type mtry(mtrySEXP);
    Rcpp::traits::input_parameter< unsigned int >::type min_node_size(min_node_sizeSEXP);
    Rcpp::traits::input_parameter< double >::type max_depth(max_depthSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type nsplits(nsplitsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type splitrule(splitruleSEXP);
    Rcpp::traits::input_parameter< bool >::type honest(honestSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type response_indices(response_indicesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type feature_indices(feature_indicesSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type categorical(categoricalSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type unique(uniqueSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< size_t >::type num_event_times(num_event_timesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type splitrule_par(splitrule_parSEXP);
    rcpp_result_gen = Rcpp::wrap(JFCppTree(tree_type, df, mtry, min_node_size, max_depth, nsplits, splitrule, honest, response_indices, feature_indices, categorical, unique, seed, num_event_times, splitrule_par));
    return rcpp_result_gen;
END_RCPP
}
// JFCppTreeMultistate
List JFCppTreeMultistate(List jump_data, uint8_t max_response_length, uint8_t num_states, DataFrame df_features, unsigned int mtry, unsigned int min_node_size, double max_depth, unsigned int nsplits, CharacterVector splitrule, bool honest, NumericVector feature_indices, LogicalVector categorical, NumericVector unique, unsigned int seed, NumericVector state_weights, size_t num_event_times, NumericVector fh_weights_a, NumericVector fh_weights_b);
RcppExport SEXP _JumpForests_JFCppTreeMultistate(SEXP jump_dataSEXP, SEXP max_response_lengthSEXP, SEXP num_statesSEXP, SEXP df_featuresSEXP, SEXP mtrySEXP, SEXP min_node_sizeSEXP, SEXP max_depthSEXP, SEXP nsplitsSEXP, SEXP splitruleSEXP, SEXP honestSEXP, SEXP feature_indicesSEXP, SEXP categoricalSEXP, SEXP uniqueSEXP, SEXP seedSEXP, SEXP state_weightsSEXP, SEXP num_event_timesSEXP, SEXP fh_weights_aSEXP, SEXP fh_weights_bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type jump_data(jump_dataSEXP);
    Rcpp::traits::input_parameter< uint8_t >::type max_response_length(max_response_lengthSEXP);
    Rcpp::traits::input_parameter< uint8_t >::type num_states(num_statesSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type df_features(df_featuresSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type mtry(mtrySEXP);
    Rcpp::traits::input_parameter< unsigned int >::type min_node_size(min_node_sizeSEXP);
    Rcpp::traits::input_parameter< double >::type max_depth(max_depthSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type nsplits(nsplitsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type splitrule(splitruleSEXP);
    Rcpp::traits::input_parameter< bool >::type honest(honestSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type feature_indices(feature_indicesSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type categorical(categoricalSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type unique(uniqueSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type state_weights(state_weightsSEXP);
    Rcpp::traits::input_parameter< size_t >::type num_event_times(num_event_timesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type fh_weights_a(fh_weights_aSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type fh_weights_b(fh_weights_bSEXP);
    rcpp_result_gen = Rcpp::wrap(JFCppTreeMultistate(jump_data, max_response_length, num_states, df_features, mtry, min_node_size, max_depth, nsplits, splitrule, honest, feature_indices, categorical, unique, seed, state_weights, num_event_times, fh_weights_a, fh_weights_b));
    return rcpp_result_gen;
END_RCPP
}
// JFCppTreePredict
NumericMatrix JFCppTreePredict(const List& JFTree, DataFrame df, NumericVector feature_indices, LogicalVector categorical, NumericVector unique);
RcppExport SEXP _JumpForests_JFCppTreePredict(SEXP JFTreeSEXP, SEXP dfSEXP, SEXP feature_indicesSEXP, SEXP categoricalSEXP, SEXP uniqueSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type JFTree(JFTreeSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type df(dfSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type feature_indices(feature_indicesSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type categorical(categoricalSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type unique(uniqueSEXP);
    rcpp_result_gen = Rcpp::wrap(JFCppTreePredict(JFTree, df, feature_indices, categorical, unique));
    return rcpp_result_gen;
END_RCPP
}
// JFCppTreePredictCensoring
List JFCppTreePredictCensoring(const List& JFTree, DataFrame df, NumericVector feature_indices, LogicalVector categorical, NumericVector unique);
RcppExport SEXP _JumpForests_JFCppTreePredictCensoring(SEXP JFTreeSEXP, SEXP dfSEXP, SEXP feature_indicesSEXP, SEXP categoricalSEXP, SEXP uniqueSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type JFTree(JFTreeSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type df(dfSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type feature_indices(feature_indicesSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type categorical(categoricalSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type unique(uniqueSEXP);
    rcpp_result_gen = Rcpp::wrap(JFCppTreePredictCensoring(JFTree, df, feature_indices, categorical, unique));
    return rcpp_result_gen;
END_RCPP
}
// JFCppTreePredictMultistate
List JFCppTreePredictMultistate(const List& JFTree, DataFrame df, NumericVector feature_indices, LogicalVector categorical, NumericVector unique, bool compute_initial, bool compute_censoring);
RcppExport SEXP _JumpForests_JFCppTreePredictMultistate(SEXP JFTreeSEXP, SEXP dfSEXP, SEXP feature_indicesSEXP, SEXP categoricalSEXP, SEXP uniqueSEXP, SEXP compute_initialSEXP, SEXP compute_censoringSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type JFTree(JFTreeSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type df(dfSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type feature_indices(feature_indicesSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type categorical(categoricalSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type unique(uniqueSEXP);
    Rcpp::traits::input_parameter< bool >::type compute_initial(compute_initialSEXP);
    Rcpp::traits::input_parameter< bool >::type compute_censoring(compute_censoringSEXP);
    rcpp_result_gen = Rcpp::wrap(JFCppTreePredictMultistate(JFTree, df, feature_indices, categorical, unique, compute_initial, compute_censoring));
    return rcpp_result_gen;
END_RCPP
}
// JFCppTreeError
List JFCppTreeError(const List& JFTree, DataFrame df, NumericVector feature_indices, LogicalVector categorical, NumericVector unique, NumericVector response_indices);
RcppExport SEXP _JumpForests_JFCppTreeError(SEXP JFTreeSEXP, SEXP dfSEXP, SEXP feature_indicesSEXP, SEXP categoricalSEXP, SEXP uniqueSEXP, SEXP response_indicesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type JFTree(JFTreeSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type df(dfSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type feature_indices(feature_indicesSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type categorical(categoricalSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type unique(uniqueSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type response_indices(response_indicesSEXP);
    rcpp_result_gen = Rcpp::wrap(JFCppTreeError(JFTree, df, feature_indices, categorical, unique, response_indices));
    return rcpp_result_gen;
END_RCPP
}
// JFCppTreeErrorMultistate
List JFCppTreeErrorMultistate(const List& JFTree, uint8_t max_response_length, uint8_t num_states, List jump_data, DataFrame df_features, NumericVector feature_indices, LogicalVector categorical, NumericVector unique, NumericVector state_weights);
RcppExport SEXP _JumpForests_JFCppTreeErrorMultistate(SEXP JFTreeSEXP, SEXP max_response_lengthSEXP, SEXP num_statesSEXP, SEXP jump_dataSEXP, SEXP df_featuresSEXP, SEXP feature_indicesSEXP, SEXP categoricalSEXP, SEXP uniqueSEXP, SEXP state_weightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type JFTree(JFTreeSEXP);
    Rcpp::traits::input_parameter< uint8_t >::type max_response_length(max_response_lengthSEXP);
    Rcpp::traits::input_parameter< uint8_t >::type num_states(num_statesSEXP);
    Rcpp::traits::input_parameter< List >::type jump_data(jump_dataSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type df_features(df_featuresSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type feature_indices(feature_indicesSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type categorical(categoricalSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type unique(uniqueSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type state_weights(state_weightsSEXP);
    rcpp_result_gen = Rcpp::wrap(JFCppTreeErrorMultistate(JFTree, max_response_length, num_states, jump_data, df_features, feature_indices, categorical, unique, state_weights));
    return rcpp_result_gen;
END_RCPP
}
// JFCppForest
List JFCppForest(unsigned int tree_type, DataFrame df, unsigned int mtry, unsigned int min_node_size, double max_depth, unsigned int nsplits, CharacterVector splitrule, unsigned int ntrees, bool honest, bool swr, double sample_rate, bool double_bootstrap, NumericVector response_indices, NumericVector feature_indices, LogicalVector categorical, NumericVector unique, unsigned int seed, unsigned int nworkers, bool save_predictions, size_t num_event_times, NumericVector splitrule_par);
RcppExport SEXP _JumpForests_JFCppForest(SEXP tree_typeSEXP, SEXP dfSEXP, SEXP mtrySEXP, SEXP min_node_sizeSEXP, SEXP max_depthSEXP, SEXP nsplitsSEXP, SEXP splitruleSEXP, SEXP ntreesSEXP, SEXP honestSEXP, SEXP swrSEXP, SEXP sample_rateSEXP, SEXP double_bootstrapSEXP, SEXP response_indicesSEXP, SEXP feature_indicesSEXP, SEXP categoricalSEXP, SEXP uniqueSEXP, SEXP seedSEXP, SEXP nworkersSEXP, SEXP save_predictionsSEXP, SEXP num_event_timesSEXP, SEXP splitrule_parSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< unsigned int >::type tree_type(tree_typeSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type df(dfSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type mtry(mtrySEXP);
    Rcpp::traits::input_parameter< unsigned int >::type min_node_size(min_node_sizeSEXP);
    Rcpp::traits::input_parameter< double >::type max_depth(max_depthSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type nsplits(nsplitsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type splitrule(splitruleSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type ntrees(ntreesSEXP);
    Rcpp::traits::input_parameter< bool >::type honest(honestSEXP);
    Rcpp::traits::input_parameter< bool >::type swr(swrSEXP);
    Rcpp::traits::input_parameter< double >::type sample_rate(sample_rateSEXP);
    Rcpp::traits::input_parameter< bool >::type double_bootstrap(double_bootstrapSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type response_indices(response_indicesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type feature_indices(feature_indicesSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type categorical(categoricalSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type unique(uniqueSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type nworkers(nworkersSEXP);
    Rcpp::traits::input_parameter< bool >::type save_predictions(save_predictionsSEXP);
    Rcpp::traits::input_parameter< size_t >::type num_event_times(num_event_timesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type splitrule_par(splitrule_parSEXP);
    rcpp_result_gen = Rcpp::wrap(JFCppForest(tree_type, df, mtry, min_node_size, max_depth, nsplits, splitrule, ntrees, honest, swr, sample_rate, double_bootstrap, response_indices, feature_indices, categorical, unique, seed, nworkers, save_predictions, num_event_times, splitrule_par));
    return rcpp_result_gen;
END_RCPP
}
// JFCppForestMultistate
List JFCppForestMultistate(List jump_data, uint8_t max_response_length, uint8_t num_states, DataFrame df_features, unsigned int mtry, unsigned int min_node_size, double max_depth, unsigned int nsplits, CharacterVector splitrule, unsigned int ntrees, bool honest, bool swr, double sample_rate, bool double_bootstrap, NumericVector feature_indices, LogicalVector categorical, NumericVector unique, unsigned int seed, unsigned int nworkers, bool save_predictions, NumericVector state_weights, size_t num_event_times, NumericVector fh_weights_a, NumericVector fh_weights_b);
RcppExport SEXP _JumpForests_JFCppForestMultistate(SEXP jump_dataSEXP, SEXP max_response_lengthSEXP, SEXP num_statesSEXP, SEXP df_featuresSEXP, SEXP mtrySEXP, SEXP min_node_sizeSEXP, SEXP max_depthSEXP, SEXP nsplitsSEXP, SEXP splitruleSEXP, SEXP ntreesSEXP, SEXP honestSEXP, SEXP swrSEXP, SEXP sample_rateSEXP, SEXP double_bootstrapSEXP, SEXP feature_indicesSEXP, SEXP categoricalSEXP, SEXP uniqueSEXP, SEXP seedSEXP, SEXP nworkersSEXP, SEXP save_predictionsSEXP, SEXP state_weightsSEXP, SEXP num_event_timesSEXP, SEXP fh_weights_aSEXP, SEXP fh_weights_bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type jump_data(jump_dataSEXP);
    Rcpp::traits::input_parameter< uint8_t >::type max_response_length(max_response_lengthSEXP);
    Rcpp::traits::input_parameter< uint8_t >::type num_states(num_statesSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type df_features(df_featuresSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type mtry(mtrySEXP);
    Rcpp::traits::input_parameter< unsigned int >::type min_node_size(min_node_sizeSEXP);
    Rcpp::traits::input_parameter< double >::type max_depth(max_depthSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type nsplits(nsplitsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type splitrule(splitruleSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type ntrees(ntreesSEXP);
    Rcpp::traits::input_parameter< bool >::type honest(honestSEXP);
    Rcpp::traits::input_parameter< bool >::type swr(swrSEXP);
    Rcpp::traits::input_parameter< double >::type sample_rate(sample_rateSEXP);
    Rcpp::traits::input_parameter< bool >::type double_bootstrap(double_bootstrapSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type feature_indices(feature_indicesSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type categorical(categoricalSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type unique(uniqueSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type nworkers(nworkersSEXP);
    Rcpp::traits::input_parameter< bool >::type save_predictions(save_predictionsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type state_weights(state_weightsSEXP);
    Rcpp::traits::input_parameter< size_t >::type num_event_times(num_event_timesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type fh_weights_a(fh_weights_aSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type fh_weights_b(fh_weights_bSEXP);
    rcpp_result_gen = Rcpp::wrap(JFCppForestMultistate(jump_data, max_response_length, num_states, df_features, mtry, min_node_size, max_depth, nsplits, splitrule, ntrees, honest, swr, sample_rate, double_bootstrap, feature_indices, categorical, unique, seed, nworkers, save_predictions, state_weights, num_event_times, fh_weights_a, fh_weights_b));
    return rcpp_result_gen;
END_RCPP
}
// JFCppForestPredictTraining
void JFCppForestPredictTraining(List& JFForest);
RcppExport SEXP _JumpForests_JFCppForestPredictTraining(SEXP JFForestSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List& >::type JFForest(JFForestSEXP);
    JFCppForestPredictTraining(JFForest);
    return R_NilValue;
END_RCPP
}
// JFCppForestPredict
NumericMatrix JFCppForestPredict(const List& JFForest, DataFrame df, NumericVector feature_indices, LogicalVector categorical, NumericVector unique);
RcppExport SEXP _JumpForests_JFCppForestPredict(SEXP JFForestSEXP, SEXP dfSEXP, SEXP feature_indicesSEXP, SEXP categoricalSEXP, SEXP uniqueSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type JFForest(JFForestSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type df(dfSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type feature_indices(feature_indicesSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type categorical(categoricalSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type unique(uniqueSEXP);
    rcpp_result_gen = Rcpp::wrap(JFCppForestPredict(JFForest, df, feature_indices, categorical, unique));
    return rcpp_result_gen;
END_RCPP
}
// JFCppForestPredictCensoring
List JFCppForestPredictCensoring(const List& JFForest, DataFrame df, NumericVector feature_indices, LogicalVector categorical, NumericVector unique);
RcppExport SEXP _JumpForests_JFCppForestPredictCensoring(SEXP JFForestSEXP, SEXP dfSEXP, SEXP feature_indicesSEXP, SEXP categoricalSEXP, SEXP uniqueSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type JFForest(JFForestSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type df(dfSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type feature_indices(feature_indicesSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type categorical(categoricalSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type unique(uniqueSEXP);
    rcpp_result_gen = Rcpp::wrap(JFCppForestPredictCensoring(JFForest, df, feature_indices, categorical, unique));
    return rcpp_result_gen;
END_RCPP
}
// JFCppForestPredictMultistate
List JFCppForestPredictMultistate(const List& JFForest, DataFrame df, NumericVector feature_indices, LogicalVector categorical, NumericVector unique, bool compute_initial);
RcppExport SEXP _JumpForests_JFCppForestPredictMultistate(SEXP JFForestSEXP, SEXP dfSEXP, SEXP feature_indicesSEXP, SEXP categoricalSEXP, SEXP uniqueSEXP, SEXP compute_initialSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type JFForest(JFForestSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type df(dfSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type feature_indices(feature_indicesSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type categorical(categoricalSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type unique(uniqueSEXP);
    Rcpp::traits::input_parameter< bool >::type compute_initial(compute_initialSEXP);
    rcpp_result_gen = Rcpp::wrap(JFCppForestPredictMultistate(JFForest, df, feature_indices, categorical, unique, compute_initial));
    return rcpp_result_gen;
END_RCPP
}
// JFCppForestErrorSurvivalExternal
List JFCppForestErrorSurvivalExternal(List& JFForest);
RcppExport SEXP _JumpForests_JFCppForestErrorSurvivalExternal(SEXP JFForestSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List& >::type JFForest(JFForestSEXP);
    rcpp_result_gen = Rcpp::wrap(JFCppForestErrorSurvivalExternal(JFForest));
    return rcpp_result_gen;
END_RCPP
}
// JFCppForestErrorMultistateExternal
List JFCppForestErrorMultistateExternal(List& JFForest, NumericVector state_weights);
RcppExport SEXP _JumpForests_JFCppForestErrorMultistateExternal(SEXP JFForestSEXP, SEXP state_weightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List& >::type JFForest(JFForestSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type state_weights(state_weightsSEXP);
    rcpp_result_gen = Rcpp::wrap(JFCppForestErrorMultistateExternal(JFForest, state_weights));
    return rcpp_result_gen;
END_RCPP
}
// JFCppForestError
List JFCppForestError(const List& JFForest, DataFrame df, NumericVector feature_indices, LogicalVector categorical, NumericVector unique, NumericVector response_indices);
RcppExport SEXP _JumpForests_JFCppForestError(SEXP JFForestSEXP, SEXP dfSEXP, SEXP feature_indicesSEXP, SEXP categoricalSEXP, SEXP uniqueSEXP, SEXP response_indicesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type JFForest(JFForestSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type df(dfSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type feature_indices(feature_indicesSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type categorical(categoricalSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type unique(uniqueSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type response_indices(response_indicesSEXP);
    rcpp_result_gen = Rcpp::wrap(JFCppForestError(JFForest, df, feature_indices, categorical, unique, response_indices));
    return rcpp_result_gen;
END_RCPP
}
// JFCppForestErrorMultistate
List JFCppForestErrorMultistate(const List& JFForest, uint8_t max_response_length, uint8_t num_states, List jump_data, DataFrame df_features, NumericVector feature_indices, LogicalVector categorical, NumericVector unique, NumericVector state_weights);
RcppExport SEXP _JumpForests_JFCppForestErrorMultistate(SEXP JFForestSEXP, SEXP max_response_lengthSEXP, SEXP num_statesSEXP, SEXP jump_dataSEXP, SEXP df_featuresSEXP, SEXP feature_indicesSEXP, SEXP categoricalSEXP, SEXP uniqueSEXP, SEXP state_weightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type JFForest(JFForestSEXP);
    Rcpp::traits::input_parameter< uint8_t >::type max_response_length(max_response_lengthSEXP);
    Rcpp::traits::input_parameter< uint8_t >::type num_states(num_statesSEXP);
    Rcpp::traits::input_parameter< List >::type jump_data(jump_dataSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type df_features(df_featuresSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type feature_indices(feature_indicesSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type categorical(categoricalSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type unique(uniqueSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type state_weights(state_weightsSEXP);
    rcpp_result_gen = Rcpp::wrap(JFCppForestErrorMultistate(JFForest, max_response_length, num_states, jump_data, df_features, feature_indices, categorical, unique, state_weights));
    return rcpp_result_gen;
END_RCPP
}
// JFCppForestVIMPFeature
double JFCppForestVIMPFeature(const List& JFForest, CharacterVector feature_name, int feature_seed, CharacterVector method, CharacterVector loss);
RcppExport SEXP _JumpForests_JFCppForestVIMPFeature(SEXP JFForestSEXP, SEXP feature_nameSEXP, SEXP feature_seedSEXP, SEXP methodSEXP, SEXP lossSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type JFForest(JFForestSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type feature_name(feature_nameSEXP);
    Rcpp::traits::input_parameter< int >::type feature_seed(feature_seedSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type method(methodSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type loss(lossSEXP);
    rcpp_result_gen = Rcpp::wrap(JFCppForestVIMPFeature(JFForest, feature_name, feature_seed, method, loss));
    return rcpp_result_gen;
END_RCPP
}
// JFCppForestVIMP
List JFCppForestVIMP(List& JFForest, int seed, CharacterVector method, CharacterVector loss);
RcppExport SEXP _JumpForests_JFCppForestVIMP(SEXP JFForestSEXP, SEXP seedSEXP, SEXP methodSEXP, SEXP lossSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List& >::type JFForest(JFForestSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type method(methodSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type loss(lossSEXP);
    rcpp_result_gen = Rcpp::wrap(JFCppForestVIMP(JFForest, seed, method, loss));
    return rcpp_result_gen;
END_RCPP
}
// getTreeTable
List getTreeTable(SEXP tree_sexp);
RcppExport SEXP _JumpForests_getTreeTable(SEXP tree_sexpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type tree_sexp(tree_sexpSEXP);
    rcpp_result_gen = Rcpp::wrap(getTreeTable(tree_sexp));
    return rcpp_result_gen;
END_RCPP
}
// df_test
void df_test(DataFrame data, NumericVector response_indices, NumericVector feature_indices, LogicalVector categorical, NumericVector unique);
RcppExport SEXP _JumpForests_df_test(SEXP dataSEXP, SEXP response_indicesSEXP, SEXP feature_indicesSEXP, SEXP categoricalSEXP, SEXP uniqueSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type data(dataSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type response_indices(response_indicesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type feature_indices(feature_indicesSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type categorical(categoricalSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type unique(uniqueSEXP);
    df_test(data, response_indices, feature_indices, categorical, unique);
    return R_NilValue;
END_RCPP
}
// testData
void testData(const DataFrame& df, const NumericVector& response_indices, const NumericVector& feature_indices, const LogicalVector& categorical, const NumericVector& unique);
RcppExport SEXP _JumpForests_testData(SEXP dfSEXP, SEXP response_indicesSEXP, SEXP feature_indicesSEXP, SEXP categoricalSEXP, SEXP uniqueSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const DataFrame& >::type df(dfSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type response_indices(response_indicesSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type feature_indices(feature_indicesSEXP);
    Rcpp::traits::input_parameter< const LogicalVector& >::type categorical(categoricalSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type unique(uniqueSEXP);
    testData(df, response_indices, feature_indices, categorical, unique);
    return R_NilValue;
END_RCPP
}
// testDataMultistate
void testDataMultistate(const List& jump_data, uint8_t max_response_length, uint8_t num_states, DataFrame& feature_df, const NumericVector& feature_indices, const LogicalVector& categorical, const NumericVector& unique);
RcppExport SEXP _JumpForests_testDataMultistate(SEXP jump_dataSEXP, SEXP max_response_lengthSEXP, SEXP num_statesSEXP, SEXP feature_dfSEXP, SEXP feature_indicesSEXP, SEXP categoricalSEXP, SEXP uniqueSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type jump_data(jump_dataSEXP);
    Rcpp::traits::input_parameter< uint8_t >::type max_response_length(max_response_lengthSEXP);
    Rcpp::traits::input_parameter< uint8_t >::type num_states(num_statesSEXP);
    Rcpp::traits::input_parameter< DataFrame& >::type feature_df(feature_dfSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type feature_indices(feature_indicesSEXP);
    Rcpp::traits::input_parameter< const LogicalVector& >::type categorical(categoricalSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type unique(uniqueSEXP);
    testDataMultistate(jump_data, max_response_length, num_states, feature_df, feature_indices, categorical, unique);
    return R_NilValue;
END_RCPP
}
// testUniqueEventTimesThinning
List testUniqueEventTimesThinning(const NumericVector& unique_event_times, size_t num_event_times);
RcppExport SEXP _JumpForests_testUniqueEventTimesThinning(SEXP unique_event_timesSEXP, SEXP num_event_timesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type unique_event_times(unique_event_timesSEXP);
    Rcpp::traits::input_parameter< size_t >::type num_event_times(num_event_timesSEXP);
    rcpp_result_gen = Rcpp::wrap(testUniqueEventTimesThinning(unique_event_times, num_event_times));
    return rcpp_result_gen;
END_RCPP
}
// test_omp
void test_omp();
RcppExport SEXP _JumpForests_test_omp() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    test_omp();
    return R_NilValue;
END_RCPP
}
// getNodeSize
int getNodeSize(const List& JFTree, const NumericVector& x);
RcppExport SEXP _JumpForests_getNodeSize(SEXP JFTreeSEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type JFTree(JFTreeSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(getNodeSize(JFTree, x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_JumpForests_JFCppTree", (DL_FUNC) &_JumpForests_JFCppTree, 15},
    {"_JumpForests_JFCppTreeMultistate", (DL_FUNC) &_JumpForests_JFCppTreeMultistate, 18},
    {"_JumpForests_JFCppTreePredict", (DL_FUNC) &_JumpForests_JFCppTreePredict, 5},
    {"_JumpForests_JFCppTreePredictCensoring", (DL_FUNC) &_JumpForests_JFCppTreePredictCensoring, 5},
    {"_JumpForests_JFCppTreePredictMultistate", (DL_FUNC) &_JumpForests_JFCppTreePredictMultistate, 7},
    {"_JumpForests_JFCppTreeError", (DL_FUNC) &_JumpForests_JFCppTreeError, 6},
    {"_JumpForests_JFCppTreeErrorMultistate", (DL_FUNC) &_JumpForests_JFCppTreeErrorMultistate, 9},
    {"_JumpForests_JFCppForest", (DL_FUNC) &_JumpForests_JFCppForest, 21},
    {"_JumpForests_JFCppForestMultistate", (DL_FUNC) &_JumpForests_JFCppForestMultistate, 24},
    {"_JumpForests_JFCppForestPredictTraining", (DL_FUNC) &_JumpForests_JFCppForestPredictTraining, 1},
    {"_JumpForests_JFCppForestPredict", (DL_FUNC) &_JumpForests_JFCppForestPredict, 5},
    {"_JumpForests_JFCppForestPredictCensoring", (DL_FUNC) &_JumpForests_JFCppForestPredictCensoring, 5},
    {"_JumpForests_JFCppForestPredictMultistate", (DL_FUNC) &_JumpForests_JFCppForestPredictMultistate, 6},
    {"_JumpForests_JFCppForestErrorSurvivalExternal", (DL_FUNC) &_JumpForests_JFCppForestErrorSurvivalExternal, 1},
    {"_JumpForests_JFCppForestErrorMultistateExternal", (DL_FUNC) &_JumpForests_JFCppForestErrorMultistateExternal, 2},
    {"_JumpForests_JFCppForestError", (DL_FUNC) &_JumpForests_JFCppForestError, 6},
    {"_JumpForests_JFCppForestErrorMultistate", (DL_FUNC) &_JumpForests_JFCppForestErrorMultistate, 9},
    {"_JumpForests_JFCppForestVIMPFeature", (DL_FUNC) &_JumpForests_JFCppForestVIMPFeature, 5},
    {"_JumpForests_JFCppForestVIMP", (DL_FUNC) &_JumpForests_JFCppForestVIMP, 4},
    {"_JumpForests_getTreeTable", (DL_FUNC) &_JumpForests_getTreeTable, 1},
    {"_JumpForests_df_test", (DL_FUNC) &_JumpForests_df_test, 5},
    {"_JumpForests_testData", (DL_FUNC) &_JumpForests_testData, 5},
    {"_JumpForests_testDataMultistate", (DL_FUNC) &_JumpForests_testDataMultistate, 7},
    {"_JumpForests_testUniqueEventTimesThinning", (DL_FUNC) &_JumpForests_testUniqueEventTimesThinning, 2},
    {"_JumpForests_test_omp", (DL_FUNC) &_JumpForests_test_omp, 0},
    {"_JumpForests_getNodeSize", (DL_FUNC) &_JumpForests_getNodeSize, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_JumpForests(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
