# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

JFCppTree <- function(tree_type, df, mtry, min_node_size, nsplits, splitrule, honest, response_indices, feature_indices, categorical, unique, seed) {
    .Call(`_JumpForests_JFCppTree`, tree_type, df, mtry, min_node_size, nsplits, splitrule, honest, response_indices, feature_indices, categorical, unique, seed)
}

JFCppTreeMM <- function(jump_data, max_response_length, num_states, df_features, mtry, min_node_size, nsplits, splitrule, honest, feature_indices, categorical, unique, seed) {
    .Call(`_JumpForests_JFCppTreeMM`, jump_data, max_response_length, num_states, df_features, mtry, min_node_size, nsplits, splitrule, honest, feature_indices, categorical, unique, seed)
}

JFCppTreePredict <- function(JFTree, df, feature_indices, categorical, unique) {
    .Call(`_JumpForests_JFCppTreePredict`, JFTree, df, feature_indices, categorical, unique)
}

JFCppTreeError <- function(JFTree, df, feature_indices, categorical, unique, response_indices) {
    .Call(`_JumpForests_JFCppTreeError`, JFTree, df, feature_indices, categorical, unique, response_indices)
}

JFCppForest <- function(tree_type, df, mtry, min_node_size, nsplits, splitrule, ntrees, honest, swr, sample_rate, response_indices, feature_indices, categorical, unique, seed, nworkers) {
    .Call(`_JumpForests_JFCppForest`, tree_type, df, mtry, min_node_size, nsplits, splitrule, ntrees, honest, swr, sample_rate, response_indices, feature_indices, categorical, unique, seed, nworkers)
}

JFCppForestPredict <- function(JFForest, df, feature_indices, categorical, unique) {
    .Call(`_JumpForests_JFCppForestPredict`, JFForest, df, feature_indices, categorical, unique)
}

JFCppForestError <- function(JFForest, df, feature_indices, categorical, unique, response_indices) {
    .Call(`_JumpForests_JFCppForestError`, JFForest, df, feature_indices, categorical, unique, response_indices)
}

JFCppForestVIMPFeature <- function(JFForest, feature_name, feature_seed, method) {
    .Call(`_JumpForests_JFCppForestVIMPFeature`, JFForest, feature_name, feature_seed, method)
}

JFCppForestVIMP <- function(JFForest, seed, method) {
    .Call(`_JumpForests_JFCppForestVIMP`, JFForest, seed, method)
}

getTreeTable <- function(tree_sexp) {
    .Call(`_JumpForests_getTreeTable`, tree_sexp)
}

df_test <- function(data, response_indices, feature_indices, categorical, unique) {
    invisible(.Call(`_JumpForests_df_test`, data, response_indices, feature_indices, categorical, unique))
}

testData <- function(df, response_indices, feature_indices, categorical, unique) {
    invisible(.Call(`_JumpForests_testData`, df, response_indices, feature_indices, categorical, unique))
}

test_omp <- function() {
    invisible(.Call(`_JumpForests_test_omp`))
}

testList <- function() {
    .Call(`_JumpForests_testList`)
}

extract_column <- function(data, index) {
    .Call(`_JumpForests_extract_column`, data, index)
}

rcpp_hello_world <- function() {
    .Call(`_JumpForests_rcpp_hello_world`)
}

square_cpp <- function(x) {
    .Call(`_JumpForests_square_cpp`, x)
}

timesTwoMatrix <- function(mat) {
    .Call(`_JumpForests_timesTwoMatrix`, mat)
}

sampler <- function(n, k) {
    invisible(.Call(`_JumpForests_sampler`, n, k))
}

silly_sampler <- function(k) {
    invisible(.Call(`_JumpForests_silly_sampler`, k))
}

sampler_wrapper <- function(n, k, wr) {
    invisible(.Call(`_JumpForests_sampler_wrapper`, n, k, wr))
}

