# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

JFCppTree <- function(tree_type, df, mtry, min_node_size, max_depth, nsplits, splitrule, honest, response_indices, feature_indices, categorical, unique, seed, num_event_times = 0L, splitrule_par = numeric()) {
    .Call(`_JumpForests_JFCppTree`, tree_type, df, mtry, min_node_size, max_depth, nsplits, splitrule, honest, response_indices, feature_indices, categorical, unique, seed, num_event_times, splitrule_par)
}

JFCppTreeMultistate <- function(jump_data, max_response_length, num_states, df_features, mtry, min_node_size, max_depth, nsplits, splitrule, honest, feature_indices, categorical, unique, seed, state_weights, num_event_times, fh_weights_a, fh_weights_b) {
    .Call(`_JumpForests_JFCppTreeMultistate`, jump_data, max_response_length, num_states, df_features, mtry, min_node_size, max_depth, nsplits, splitrule, honest, feature_indices, categorical, unique, seed, state_weights, num_event_times, fh_weights_a, fh_weights_b)
}

JFCppTreePredict <- function(JFTree, df, feature_indices, categorical, unique) {
    .Call(`_JumpForests_JFCppTreePredict`, JFTree, df, feature_indices, categorical, unique)
}

JFCppTreePredictCensoring <- function(JFTree, df, feature_indices, categorical, unique) {
    .Call(`_JumpForests_JFCppTreePredictCensoring`, JFTree, df, feature_indices, categorical, unique)
}

JFCppTreePredictMultistate <- function(JFTree, df, feature_indices, categorical, unique, compute_initial, compute_censoring) {
    .Call(`_JumpForests_JFCppTreePredictMultistate`, JFTree, df, feature_indices, categorical, unique, compute_initial, compute_censoring)
}

JFCppTreeError <- function(JFTree, df, feature_indices, categorical, unique, response_indices) {
    .Call(`_JumpForests_JFCppTreeError`, JFTree, df, feature_indices, categorical, unique, response_indices)
}

JFCppTreeErrorMultistate <- function(JFTree, max_response_length, num_states, jump_data, df_features, feature_indices, categorical, unique, state_weights) {
    .Call(`_JumpForests_JFCppTreeErrorMultistate`, JFTree, max_response_length, num_states, jump_data, df_features, feature_indices, categorical, unique, state_weights)
}

JFCppForest <- function(tree_type, df, mtry, min_node_size, max_depth, nsplits, splitrule, ntrees, honest, swr, sample_rate, double_bootstrap, response_indices, feature_indices, categorical, unique, seed, nworkers, save_predictions, num_event_times = 0L, splitrule_par = numeric()) {
    .Call(`_JumpForests_JFCppForest`, tree_type, df, mtry, min_node_size, max_depth, nsplits, splitrule, ntrees, honest, swr, sample_rate, double_bootstrap, response_indices, feature_indices, categorical, unique, seed, nworkers, save_predictions, num_event_times, splitrule_par)
}

JFCppForestMultistate <- function(jump_data, max_response_length, num_states, df_features, mtry, min_node_size, max_depth, nsplits, splitrule, ntrees, honest, swr, sample_rate, double_bootstrap, feature_indices, categorical, unique, seed, nworkers, save_predictions, state_weights, num_event_times, fh_weights_a, fh_weights_b) {
    .Call(`_JumpForests_JFCppForestMultistate`, jump_data, max_response_length, num_states, df_features, mtry, min_node_size, max_depth, nsplits, splitrule, ntrees, honest, swr, sample_rate, double_bootstrap, feature_indices, categorical, unique, seed, nworkers, save_predictions, state_weights, num_event_times, fh_weights_a, fh_weights_b)
}

JFCppForestPredictTraining <- function(JFForest) {
    invisible(.Call(`_JumpForests_JFCppForestPredictTraining`, JFForest))
}

JFCppForestPredict <- function(JFForest, df, feature_indices, categorical, unique) {
    .Call(`_JumpForests_JFCppForestPredict`, JFForest, df, feature_indices, categorical, unique)
}

JFCppForestPredictCensoring <- function(JFForest, df, feature_indices, categorical, unique) {
    .Call(`_JumpForests_JFCppForestPredictCensoring`, JFForest, df, feature_indices, categorical, unique)
}

JFCppForestPredictMultistate <- function(JFForest, df, feature_indices, categorical, unique, compute_initial) {
    .Call(`_JumpForests_JFCppForestPredictMultistate`, JFForest, df, feature_indices, categorical, unique, compute_initial)
}

JFCppForestErrorSurvivalExternal <- function(JFForest) {
    .Call(`_JumpForests_JFCppForestErrorSurvivalExternal`, JFForest)
}

JFCppForestErrorMultistateExternal <- function(JFForest, state_weights) {
    .Call(`_JumpForests_JFCppForestErrorMultistateExternal`, JFForest, state_weights)
}

JFCppForestError <- function(JFForest, df, feature_indices, categorical, unique, response_indices) {
    .Call(`_JumpForests_JFCppForestError`, JFForest, df, feature_indices, categorical, unique, response_indices)
}

JFCppForestErrorMultistate <- function(JFForest, max_response_length, num_states, jump_data, df_features, feature_indices, categorical, unique, state_weights) {
    .Call(`_JumpForests_JFCppForestErrorMultistate`, JFForest, max_response_length, num_states, jump_data, df_features, feature_indices, categorical, unique, state_weights)
}

JFCppForestVIMPFeature <- function(JFForest, feature_name, feature_seed, method, loss) {
    .Call(`_JumpForests_JFCppForestVIMPFeature`, JFForest, feature_name, feature_seed, method, loss)
}

JFCppForestVIMP <- function(JFForest, seed, method, loss) {
    .Call(`_JumpForests_JFCppForestVIMP`, JFForest, seed, method, loss)
}

getTreeTable <- function(tree_sexp) {
    .Call(`_JumpForests_getTreeTable`, tree_sexp)
}

df_test <- function(data, response_indices, feature_indices, categorical, unique) {
    invisible(.Call(`_JumpForests_df_test`, data, response_indices, feature_indices, categorical, unique))
}

testData <- function(df, response_indices, feature_indices, categorical, unique) {
    invisible(.Call(`_JumpForests_testData`, df, response_indices, feature_indices, categorical, unique))
}

testDataMultistate <- function(jump_data, max_response_length, num_states, feature_df, feature_indices, categorical, unique) {
    invisible(.Call(`_JumpForests_testDataMultistate`, jump_data, max_response_length, num_states, feature_df, feature_indices, categorical, unique))
}

testUniqueEventTimesThinning <- function(unique_event_times, num_event_times) {
    .Call(`_JumpForests_testUniqueEventTimesThinning`, unique_event_times, num_event_times)
}

test_omp <- function() {
    invisible(.Call(`_JumpForests_test_omp`))
}

getNodeSize <- function(JFTree, x) {
    .Call(`_JumpForests_getNodeSize`, JFTree, x)
}

