# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

JFCppTree <- function(tree_type, df, mtry, min_node_size, nsplits, splitrule, honest, response_indices, feature_indices, categorical, unique, seed, num_event_times = 0L) {
    .Call(`_JumpForests_JFCppTree`, tree_type, df, mtry, min_node_size, nsplits, splitrule, honest, response_indices, feature_indices, categorical, unique, seed, num_event_times)
}

JFCppTreeMM <- function(jump_data, max_response_length, num_states, df_features, mtry, min_node_size, nsplits, splitrule, honest, feature_indices, categorical, unique, seed, num_event_times = 0L) {
    .Call(`_JumpForests_JFCppTreeMM`, jump_data, max_response_length, num_states, df_features, mtry, min_node_size, nsplits, splitrule, honest, feature_indices, categorical, unique, seed, num_event_times)
}

JFCppTreePredict <- function(JFTree, df, feature_indices, categorical, unique) {
    .Call(`_JumpForests_JFCppTreePredict`, JFTree, df, feature_indices, categorical, unique)
}

JFCppTreePredictCensoring <- function(JFTree, df, feature_indices, categorical, unique) {
    .Call(`_JumpForests_JFCppTreePredictCensoring`, JFTree, df, feature_indices, categorical, unique)
}

JFCppTreePredictMM <- function(JFTree, df, feature_indices, categorical, unique, compute_initial, compute_censoring) {
    .Call(`_JumpForests_JFCppTreePredictMM`, JFTree, df, feature_indices, categorical, unique, compute_initial, compute_censoring)
}

JFCppTreeError <- function(JFTree, df, feature_indices, categorical, unique, response_indices) {
    .Call(`_JumpForests_JFCppTreeError`, JFTree, df, feature_indices, categorical, unique, response_indices)
}

JFCppTreeErrorMM <- function(JFTree, max_response_length, num_states, jump_data, df_features, feature_indices, categorical, unique) {
    .Call(`_JumpForests_JFCppTreeErrorMM`, JFTree, max_response_length, num_states, jump_data, df_features, feature_indices, categorical, unique)
}

JFCppForest <- function(tree_type, df, mtry, min_node_size, nsplits, splitrule, ntrees, honest, swr, sample_rate, double_bootstrap, response_indices, feature_indices, categorical, unique, seed, nworkers, save_predictions, num_event_times = 0L) {
    .Call(`_JumpForests_JFCppForest`, tree_type, df, mtry, min_node_size, nsplits, splitrule, ntrees, honest, swr, sample_rate, double_bootstrap, response_indices, feature_indices, categorical, unique, seed, nworkers, save_predictions, num_event_times)
}

JFCppForestMM <- function(jump_data, max_response_length, num_states, df_features, mtry, min_node_size, nsplits, splitrule, ntrees, honest, swr, sample_rate, double_bootstrap, feature_indices, categorical, unique, seed, nworkers, save_predictions, num_event_times = 0L) {
    .Call(`_JumpForests_JFCppForestMM`, jump_data, max_response_length, num_states, df_features, mtry, min_node_size, nsplits, splitrule, ntrees, honest, swr, sample_rate, double_bootstrap, feature_indices, categorical, unique, seed, nworkers, save_predictions, num_event_times)
}

JFCppForestPredictTraining <- function(JFForest) {
    invisible(.Call(`_JumpForests_JFCppForestPredictTraining`, JFForest))
}

JFCppForestPredict <- function(JFForest, df, feature_indices, categorical, unique) {
    .Call(`_JumpForests_JFCppForestPredict`, JFForest, df, feature_indices, categorical, unique)
}

JFCppForestPredictCensoring <- function(JFForest, df, feature_indices, categorical, unique) {
    .Call(`_JumpForests_JFCppForestPredictCensoring`, JFForest, df, feature_indices, categorical, unique)
}

JFCppForestPredictMM <- function(JFForest, df, feature_indices, categorical, unique, compute_initial) {
    .Call(`_JumpForests_JFCppForestPredictMM`, JFForest, df, feature_indices, categorical, unique, compute_initial)
}

JFCppForestErrorSurvivalExternal <- function(JFForest) {
    .Call(`_JumpForests_JFCppForestErrorSurvivalExternal`, JFForest)
}

JFCppForestError <- function(JFForest, df, feature_indices, categorical, unique, response_indices) {
    .Call(`_JumpForests_JFCppForestError`, JFForest, df, feature_indices, categorical, unique, response_indices)
}

JFCppForestVIMPFeature <- function(JFForest, feature_name, feature_seed, method, loss) {
    .Call(`_JumpForests_JFCppForestVIMPFeature`, JFForest, feature_name, feature_seed, method, loss)
}

JFCppForestVIMP <- function(JFForest, seed, method, loss) {
    .Call(`_JumpForests_JFCppForestVIMP`, JFForest, seed, method, loss)
}

getTreeTable <- function(tree_sexp) {
    .Call(`_JumpForests_getTreeTable`, tree_sexp)
}

df_test <- function(data, response_indices, feature_indices, categorical, unique) {
    invisible(.Call(`_JumpForests_df_test`, data, response_indices, feature_indices, categorical, unique))
}

testData <- function(df, response_indices, feature_indices, categorical, unique) {
    invisible(.Call(`_JumpForests_testData`, df, response_indices, feature_indices, categorical, unique))
}

testDataMM <- function(jump_data, max_response_length, num_states, feature_df, feature_indices, categorical, unique) {
    invisible(.Call(`_JumpForests_testDataMM`, jump_data, max_response_length, num_states, feature_df, feature_indices, categorical, unique))
}

testUniqueEventTimesThinning <- function(unique_event_times, num_event_times) {
    .Call(`_JumpForests_testUniqueEventTimesThinning`, unique_event_times, num_event_times)
}

test_omp <- function() {
    invisible(.Call(`_JumpForests_test_omp`))
}

getNodeSize <- function(JFTree, x) {
    .Call(`_JumpForests_getNodeSize`, JFTree, x)
}

testList <- function() {
    .Call(`_JumpForests_testList`)
}

extract_column <- function(data, index) {
    .Call(`_JumpForests_extract_column`, data, index)
}

rcpp_hello_world <- function() {
    .Call(`_JumpForests_rcpp_hello_world`)
}

square_cpp <- function(x) {
    .Call(`_JumpForests_square_cpp`, x)
}

timesTwoMatrix <- function(mat) {
    .Call(`_JumpForests_timesTwoMatrix`, mat)
}

sampler <- function(n, k) {
    invisible(.Call(`_JumpForests_sampler`, n, k))
}

silly_sampler <- function(k) {
    invisible(.Call(`_JumpForests_silly_sampler`, k))
}

sampler_wrapper <- function(n, k, wr) {
    invisible(.Call(`_JumpForests_sampler_wrapper`, n, k, wr))
}

